server:
  port: 8080

spring:
  application:
    name: nauction
  datasource:
    url: jdbc:h2:mem:nauction;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: passu
  flyway:
    enabled: true
    locations: classpath:/db/migration/structure,classpath:/db/migration/data
    validate-on-migrate: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

