server:
  port: 8080

spring:
  application:
    name: nauction
  datasource:
    url: jdbc:h2:mem:nauction;DB_CLOSE_ON_EXIT=TRUE
    driverClassName: org.h2.Driver
    username: ${RDS_USERNAME:sa}
    password: ${RDS_PASSWORD:passu}
  flyway:
    enabled: true
    locations: classpath:/db/migration/structure,classpath:/db/migration/data
    validate-on-migrate: true
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false

